import GlassCard from '../components/GlassCard';
import { pipelineStages, coreModules } from '../data/mockData';
import * as Icons from 'lucide-react';

export default function ArchitecturePage() {
  return (
    <div className="p-6 md:p-10 max-w-7xl mx-auto hero-anim hero-fade">
      <header className="mb-10">
        <h1 className="text-3xl font-bold text-white font-playfair italic mb-2">System Architecture</h1>
        <p className="text-white/60">High-Level System Architecture and cognitive pipeline</p>
      </header>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-10">
        {/* Pipeline */}
        <div>
          <h2 className="text-xl font-semibold text-white mb-6">Discovery Pipeline (DAG)</h2>
          <div className="relative pl-6 border-l border-white/10 space-y-8">
            {pipelineStages.map((stage) => {
              const IconComponent = (Icons as any)[stage.icon] || Icons.Box;
              
              return (
                <div key={stage.id} className="relative">
                  <div className="absolute -left-[41px] top-1.5 p-2 bg-[#0a0a0f] rounded-full border border-white/20">
                    <IconComponent size={14} className="text-[#3b82f6]" />
                  </div>
                  <GlassCard className="p-5">
                    <h3 className="text-white font-medium mb-1">
                      <span className="text-[#3b82f6] mr-2 text-sm">{stage.id}.</span>
                      {stage.name}
                    </h3>
                    <p className="text-sm text-white/60 mb-3">{stage.description}</p>
                    <div className="flex flex-wrap gap-2">
                      {stage.modules.map(m => (
                        <span key={m} className="px-2 py-1 rounded bg-black/50 text-white/40 font-mono text-[10px] border border-white/5">
                          {m}
                        </span>
                      ))}
                    </div>
                  </GlassCard>
                </div>
              );
            })}
          </div>
        </div>

        {/* Modules Map */}
        <div>
          <h2 className="text-xl font-semibold text-white mb-6">Cognitive Core Modules</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            {coreModules.map((mod, idx) => (
              <GlassCard key={idx} className="p-5" hover>
                <h3 className="text-white font-medium mb-2">{mod.name}</h3>
                <p className="text-xs text-white/50 mb-4 line-clamp-2">{mod.description}</p>
                <div className="flex items-center justify-between border-t border-white/5 pt-3">
                  <span className="text-xs text-[#e8702a] font-mono truncate mr-2" title={mod.path}>{mod.path}</span>
                  <span className="text-xs font-medium text-white/40 shrink-0">{mod.files} files</span>
                </div>
              </GlassCard>
            ))}
          </div>

          <GlassCard className="mt-8 border-[#a855f7]/30 bg-[#a855f7]/5">
            <div className="flex items-center gap-3 mb-4">
              <Icons.ShieldAlert className="text-[#a855f7]" size={24} />
              <h2 className="text-lg font-semibold text-white">Agent Sandboxing</h2>
            </div>
            <p className="text-sm text-white/70 leading-relaxed">
              In accordance with <code className="text-[#a855f7] bg-black/30 px-1 rounded">REQ-SEC-005</code>, all Python code generated by reasoning agents is executed in isolated gVisor/Firecracker microVMs with zero outbound network access and strict quotas.
            </p>
          </GlassCard>
        </div>
      </div>
    </div>
  );
}
