import json
import os
import sys

# Add src to path to import database module
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..')))
from src.aidp.api.database import insert_reproduction, init_db

def ingest_github_issue(issue_json_path: str):
    """
    Parses a JSON export of a GitHub issue (e.g., from a GitHub Action payload)
    and inserts it into the telemetry.db.
    """
    print("==================================================")
    print(" ANTIGRAVITY PIPELINE: INGESTING REPRODUCTION")
    print("==================================================\n")

    if not os.path.exists(issue_json_path):
        print(f"[ERROR] Issue payload not found: {issue_json_path}")
        return

    with open(issue_json_path, 'r', encoding='utf-8') as f:
        payload = json.load(f)

    # Validate schema
    if 'issue' not in payload or 'body' not in payload['issue']:
        print("[ERROR] Invalid GitHub Issue payload format.")
        return

    issue = payload['issue']
    labels = [label['name'] for label in issue.get('labels', [])]
    
    if "evidence:reproduction" not in labels:
        print("[SKIPPED] Issue is not tagged as a reproduction.")
        return

    # In a real GitHub Actions environment, the body is a string that requires parsing
    # based on the Markdown generated by the YAML issue template.
    # For demonstration, we'll extract the fields via simple regex/split.
    body = issue['body']
    
    model_name = "unknown"
    leakage_rate = 0.0
    stance = "ambiguous"

    import re
    # More robust parsing
    model_match = re.search(r'### Exact Model Tag\s*\n(.*?)\s*\n', body)
    leakage_match = re.search(r'### Leakage Rate \(\%\)\s*\n(.*?)\s*\n', body)
    outcome_match = re.search(r'### Reproduction Outcome\s*\n(.*?)\s*\n', body)

    if model_match:
        model_name = model_match.group(1).strip()
    if leakage_match:
        try:
            leakage_rate = float(leakage_match.group(1).strip())
        except ValueError:
            pass
    if outcome_match:
        stance = outcome_match.group(1).strip()

    print(f"Parsed External Submission:")
    print(f" - Model: {model_name}")
    print(f" - Leakage Rate: {leakage_rate}%")
    print(f" - Stance: {stance}")

    # Ensure DB exists
    init_db()

    # Insert into telemetry
    insert_reproduction(model_name, leakage_rate, stance)
    print("\n[SUCCESS] Independent reproduction safely ingested into telemetry.db.")

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Ingest external GitHub Issues to SQLite.")
    parser.add_argument("--payload", type=str, required=True, help="Path to the GitHub Issue JSON payload.")
    args = parser.parse_args()
    
    ingest_github_issue(args.payload)
