import sys
import os
import json

sys.path.append(os.path.join(os.path.dirname(__file__), "src"))

from aidp.intelligence.providers.mock import MockProvider
from aidp.intelligence.providers.middleware import IntelligenceGateway
from aidp.intelligence.providers.routing import RoutingPolicy
from aidp.intelligence.providers.capabilities import LOCAL_MOCK_CAPABILITIES, ReasoningTier
from aidp.discovery.workflow import AutonomousDiscoveryOrchestrator

policy = RoutingPolicy()
LOCAL_MOCK_CAPABILITIES.reasoning_tier = ReasoningTier.EXPERT # Elevate so it passes min requirements
policy.register_provider("mock", MockProvider(), LOCAL_MOCK_CAPABILITIES)

gateway = IntelligenceGateway(routing_policy=policy)
orchestrator = AutonomousDiscoveryOrchestrator(gateway=gateway)

session = orchestrator.run_discovery_cycle("What is the effect of mRNA-4157 on recurrent melanoma?")

print(f"Workflow finished with state: {session.state.value}")

ledger_file = "data/epistemic_ledger.jsonl"
if os.path.exists(ledger_file):
    print(f"\nContents of {ledger_file}:")
    with open(ledger_file, "r") as f:
        for i, line in enumerate(f):
            data = json.loads(line)
            print(f"--- Claim {i} ---")
            print(f"Claim: {data.get('claim_text')}")
            print(f"Generated By: {data.get('generated_by')}")
            print(f"Verification Status: {data.get('verification_status')}")
            print(f"Confidence Score: {data.get('confidence_score')}")
            print(f"Reviews Count: {len(data.get('reviewed_by', []))}")
else:
    print(f"\n{ledger_file} not found.")
